### ISSUE TITLE
Set up Travis-CI to run linting, tests, and build_unsigned on each commit?

### ISSUE THREAD

**Issue by pdehaan** [internetarchive/FirefoxNoMore404s#31]
This _may_ be as easy as enabling Travis-CI for this repo and then creating something vaguely similar to the following .travis.yml file:

```yml
language: node_js

node_js:
- 4

script:
- npm run build_unsigned
```

I believe `npm test` gets run automatically, which should trigger ESLint linting via the `npm run lint` script.

But at the very least this will run linting and build an unsigned ZIP on each commit to make sure nothing is horribly broken.
